name: Playwright Tests with Allure Report

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install
          pip install pytest-xdist
          pip install urllib3
          pip install requests
          pip install allure-pytest
          npm install -g allure-commandline --save-dev

      - name: Run Playwright Tests
        run: |
          # Run tests in parallel using pytest-xdist and generate Allure results
          python -m pytest -n auto --alluredir=allure-results
        continue-on-error: true 
          
      - name: Generate Allure Report (HTML)
        run: |
          # Generate the Allure HTML report from the results
          allure generate --single-file allure-results --clean
          
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
