name: Run Pytest with HTML Report

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the version of Python you need

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install
        pip install pytest-xdist
        pip install urllib3
        pip install pytest-html

    # Run tests and generate the HTML report
    - name: Run tests
      run: |
        python -m pytest --disable-warnings --html=report.html

    # Upload the HTML report as an artifact
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html
